# Generated by Django 5.1.2 on 2024-12-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='img_pelicula',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
