# Generated by Django 5.1.2 on 2024-12-01 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appClientes', '0001_initial'),
        ('pagWeb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('cli_asociado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appClientes.cliente')),
                ('cod_pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagWeb.pelicula')),
            ],
        ),
    ]
